-- Revises: N/A
-- Creation Date: 2022-10-08 09:43:08 UTC
-- Reason: Initial Migration

CREATE TABLE IF NOT EXISTS "DEFAULT_ROLES" (
    "GUILD_ID" INTEGER NOT NULL,
    "ROLE_ID"  INTEGER NOT NULL,
    PRIMARY KEY("GUILD_ID")
);

CREATE TABLE IF NOT EXISTS "LOGGING" (
    "GUILD_ID"   INTEGER NOT NULL,
    "CHANNEL_ID" INTEGER NOT NULL,
    "BITS"       INTEGER NOT NULL,
    PRIMARY KEY("GUILD_ID")
);

CREATE TABLE IF NOT EXISTS "MEMECOIN" (
    "USER_ID" INTEGER NOT NULL,
    "COINS"   INTEGER DEFAULT 0 NOT NULL,
    PRIMARY KEY("USER_ID")
);

CREATE TABLE IF NOT EXISTS "PREFIXES" (
    "GUILD_ID" INTEGER NOT NULL,
    "PREFIX"   TEXT NOT NULL,
    PRIMARY KEY ("GUILD_ID", "PREFIX")
);

CREATE TABLE IF NOT EXISTS "REACTION_ROLES" (
    "GUILD_ID"   INTEGER NOT NULL,
    "CHANNEL_ID" INTEGER NOT NULL,
    "MESSAGE_ID" INTEGER NOT NULL,
    "REACTION"   TEXT NOT NULL,
    "ROLE_ID"    INTEGER NOT NULL,
    PRIMARY KEY("MESSAGE_ID", "REACTION")
);

CREATE TABLE IF NOT EXISTS "TAGS" (
    "NAME"     TEXT     NOT NULL,
    "CONTENT"  TEXT     NOT NULL,
    "GUILD_ID" INTEGER  NOT NULL,
    "OWNER_ID" INTEGER  NOT NULL,
    "USES"     INTEGER  NOT NULL,
    "CREATED"  DATETIME NOT NULL,
    PRIMARY KEY ("NAME", "GUILD_ID")
);

CREATE TABLE IF NOT EXISTS "VOICE_ROLES" (
    "GUILD_ID"   INTEGER NOT NULL,
    "CHANNEL_ID" INTEGER NOT NULL,
    "ROLE_ID"    INTEGER NOT NULL,
    PRIMARY KEY("CHANNEL_ID")
);

PRAGMA user_version = 1;