-- Revises: 004
-- Creation Date: 2024-01-06 20:17:05 UTC
-- Reason: Add Groups

CREATE TABLE IF NOT EXISTS "GROUPS" (
    "GUILD_ID"          INTEGER NOT NULL,
    "OWNER_ID"          INTEGER NOT NULL,
    "CREATED"           INTEGER NOT NULL,
    "GROUP_NAME"        TEXT NOT NULL,
    "MAX_MEMBERS"       INTEGER,
    PRIMARY KEY("GROUP_NAME", "GUILD_ID")
);

CREATE TABLE IF NOT EXISTS "GROUP_MEMBERS" (
    "MEMBER_ID"         INTEGER NOT NULL,
    "GUILD_ID"          INTEGER NOT NULL,
    "JOINED"            INTEGER NOT NULL,
    "GROUP_NAME"        TEXT NOT NULL,
    FOREIGN KEY("GROUP_NAME", "GUILD_ID") REFERENCES GROUPS("GROUP_NAME", "GUILD_ID") ON DELETE CASCADE,
    PRIMARY KEY("MEMBER_ID", "GUILD_ID", "GROUP_NAME")
);

PRAGMA user_version = 5;