-- Revises: 006
-- Creation Date: 2024-04-14 0:26:20 UTC
-- Reason: Add Unacceptable Status Tracking

CREATE TABLE IF NOT EXISTS "UNACCEPTABLE_STATUSES" (
    "SNOWFLAKE_ID"      INTEGER NOT NULL,
    "SNOWFLAKE_TYPE"    INTEGER NOT NULL,
    "FAILURE_COUNT"     INTEGER NOT NULL DEFAULT 0,
    "LAST_FAILURE"      INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY("SNOWFLAKE_ID")
);

CREATE TABLE IF NOT EXISTS "UNACCEPTABLE_STATUS_EVENTS" (
    "EVENT_ID"              TEXT NOT NULL,
    "SNOWFLAKE_ID"          INTEGER NOT NULL,
    "CAUSE_SNOWFLAKE_ID"    INTEGER NOT NULL,
    "CAUSE_SNOWFLAKE_TYPE"  INTEGER NOT NULL,
    "TIMESTAMP"             INTEGER NOT NULL,
    FOREIGN KEY("SNOWFLAKE_ID") REFERENCES UNACCEPTABLE_STATUSES("SNOWFLAKE_ID") ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY("EVENT_ID")
);

CREATE TRIGGER AGGREGATE_UNACCEPTABLE_STATUS_EVENTS
AFTER INSERT ON UNACCEPTABLE_STATUS_EVENTS
BEGIN
    UPDATE UNACCEPTABLE_STATUSES SET FAILURE_COUNT = FAILURE_COUNT + 1 WHERE SNOWFLAKE_ID = NEW.SNOWFLAKE_ID;
    UPDATE UNACCEPTABLE_STATUSES SET LAST_FAILURE = NEW.TIMESTAMP WHERE SNOWFLAKE_ID = NEW.SNOWFLAKE_ID;
END;

PRAGMA user_version = 7;