-- Revises: 007
-- Creation Date: 2024-02-12 18:05:12 UTC
-- Reason: Support Case-Sensitive User-Submitted Content Names

-- Tags --

ALTER TABLE "TAGS" RENAME TO "OLD_TAGS";

CREATE TABLE IF NOT EXISTS "TAGS" (
    "NAME"                  TEXT NOT NULL,
    "CONTENT"               TEXT NOT NULL,
    "GUILD_ID"              INTEGER NOT NULL,
    "OWNER_ID"              INTEGER NOT NULL,
    "USES"                  INTEGER NOT NULL,
    "CREATED"               DATETIME NOT NULL,
    "ALLOWED_MENTIONS"      INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY ("NAME", "GUILD_ID")
);

INSERT INTO "TAGS" (NAME, CONTENT, GUILD_ID, OWNER_ID, USES, CREATED, ALLOWED_MENTIONS)
SELECT NAME, CONTENT, GUILD_ID, OWNER_ID, USES, CREATED, ALLOWED_MENTIONS
FROM "OLD_TAGS";

DROP TABLE "OLD_TAGS";

-- Groups --

ALTER TABLE "GROUPS" RENAME TO "OLD_GROUPS";

CREATE TABLE IF NOT EXISTS "GROUPS" (
    "GUILD_ID"              INTEGER NOT NULL,
    "OWNER_ID"              INTEGER NOT NULL,
    "CREATED"               INTEGER NOT NULL,
    "GROUP_NAME"            TEXT NOT NULL,
    "MAX_MEMBERS"           INTEGER,
    "CURRENT_MEMBERS"       INTEGER NOT NULL DEFAULT 0,
    "EPHEMERAL_UPDATES"     INT NOT NULL DEFAULT 0,
    PRIMARY KEY("GROUP_NAME", "GUILD_ID")
);

ALTER TABLE "GROUP_MEMBERS" RENAME TO "OLD_GROUP_MEMBERS";

CREATE TABLE IF NOT EXISTS "GROUP_MEMBERS" (
    "GUILD_ID"          INTEGER NOT NULL,
    "MEMBER_ID"         INTEGER NOT NULL,
    "JOINED"            INTEGER NOT NULL,
    "GROUP_NAME"        TEXT NOT NULL,
    FOREIGN KEY("GROUP_NAME", "GUILD_ID") REFERENCES GROUPS("GROUP_NAME", "GUILD_ID") ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY("MEMBER_ID", "GUILD_ID", "GROUP_NAME")
);

DROP TRIGGER UPDATE_MEMBER_COUNT;
DROP TRIGGER DELETE_MEMBER_COUNT;

CREATE TRIGGER UPDATE_MEMBER_COUNT
AFTER INSERT ON GROUP_MEMBERS
BEGIN
    UPDATE GROUPS SET CURRENT_MEMBERS = CURRENT_MEMBERS + 1 WHERE GROUP_NAME = NEW.GROUP_NAME AND GUILD_ID = NEW.GUILD_ID;
END;

CREATE TRIGGER DELETE_MEMBER_COUNT
AFTER DELETE ON GROUP_MEMBERS
BEGIN
    UPDATE GROUPS SET CURRENT_MEMBERS = CURRENT_MEMBERS - 1 WHERE GROUP_NAME = OLD.GROUP_NAME AND GUILD_ID = OLD.GUILD_ID;
END;

INSERT INTO "GROUPS" (GUILD_ID, OWNER_ID, CREATED, GROUP_NAME, MAX_MEMBERS, EPHEMERAL_UPDATES)
SELECT GUILD_ID, OWNER_ID, CREATED, GROUP_NAME, MAX_MEMBERS, EPHEMERAL_UPDATES
FROM "OLD_GROUPS";

INSERT INTO "GROUP_MEMBERS" (GUILD_ID, MEMBER_ID, JOINED, GROUP_NAME)
SELECT GUILD_ID, MEMBER_ID, JOINED, GROUP_NAME
FROM "OLD_GROUP_MEMBERS";

DROP TABLE "OLD_GROUPS";
DROP TABLE "OLD_GROUP_MEMBERS";

PRAGMA user_version = 7;